---
title: "visualization_eda_10032019"
author: "Mary Knoop"
date: "10/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Lecture notes
#weather dataset
```{r load_df}
library(tidyverse)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

#Group by and counting 
```{r group_by_counting}
weather_df %>%
  group_by(name, month)

```

#first group by and then count the number of obseravations using the summary command -- creates new dataframe
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n())

```

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_unique = n_distinct(date)
  )

```

```{r}
weather_df %>%
  count(name, month)
```
```{r}
#rename count variable to n_days
weather_df %>%
  count(month, name = "n_days")
```


#2x2 tables
```{r}
#exposure is either Central Park or Waterhold therefore make expsoure not Waikiki , outome is cold or not cold
#case when helps to make new variable
#true "" command gives you a blank spot 
#janitor command allows it to 
weather_df %>% 
    filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >=5 ~ "not_cold",
      TRUE     ~ ""
  )) %>% 
 janitor::tabyl(name, cold)

```

#na.rm = TRUE takes the NA out of the dataset so a mean or median can be computed correctly
```{r}
weather_df %>%
  group_by(name) %>%
  summarize(
    n = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax),
    median_prcp = median(prcp, na.rm = TRUE))

```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax),
    median_prcp = median(prcp, na.rm = TRUE)
    )%>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")

```



